import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Archive, CheckCircle2, CircleAlert, Clock3, Fingerprint, ScanSearch } from "lucide-react";
import { AppShell } from "@/components/identia-app-shell";
import { Button } from "@/components/ui/button";
import { accounts, cases } from "@/lib/identia-data";

export const Route = createFileRoute("/dashboard")({
  head: () => ({ meta: [{ title: "Dashboard — IDENTIA" }, { name: "description", content: "Identity protection overview and recent impersonation signals." }, { property: "og:title", content: "Dashboard — IDENTIA" }, { property: "og:description", content: "Review identity coverage, suspicious accounts, and saved cases." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Dashboard,
});

function Dashboard() {
  const metrics = [{ label: "Verified accounts", value: "3", detail: "Across 3 platforms", icon: CheckCircle2, tone: "bg-teal-soft text-teal" }, { label: "Suspicious accounts", value: "2", detail: "1 needs review", icon: CircleAlert, tone: "bg-plum-soft text-plum" }, { label: "Saved cases", value: "4", detail: "28 evidence items", icon: Archive, tone: "bg-amber-soft text-foreground" }];
  return <AppShell eyebrow="Overview" title="Good afternoon, Maya"><div className="flex flex-col gap-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="max-w-2xl text-sm leading-6 text-muted-foreground">Your identity coverage is strong. One new profile match needs your attention.</p></div><Button asChild><Link to="/shadow-check"><ScanSearch />Run shadow check</Link></Button></div>
    <section className="grid gap-5 md:grid-cols-3">{metrics.map(({ label,value,detail,icon:Icon,tone }) => <article key={label} className="identia-card p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className="mt-2 font-display text-4xl font-bold text-primary">{value}</p></div><span className={`grid size-10 place-items-center rounded-lg ${tone}`}><Icon className="size-5" /></span></div><p className="mt-5 border-t border-border pt-4 text-xs text-muted-foreground">{detail}</p></article>)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.55fr_1fr]"><div className="identia-card overflow-hidden"><div className="flex items-center justify-between border-b border-border p-5"><div><h2 className="font-bold">Recent signals</h2><p className="mt-1 text-xs text-muted-foreground">Matches detected across public profiles</p></div><Button variant="ghost" size="sm" asChild><Link to="/evidence-locker">View all <ArrowRight /></Link></Button></div><div className="divide-y divide-border">{cases.slice(0,3).map((item) => <div key={item.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-plum-soft text-plum"><CircleAlert className="size-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-bold">{item.title}</p><span className="rounded bg-amber-soft px-2 py-0.5 text-[10px] font-bold text-foreground">{item.risk}</span></div><p className="mt-1 truncate text-xs text-muted-foreground">{item.handle} · {item.platform}</p></div><div className="text-left sm:text-right"><p className="text-xs font-semibold">{item.evidence} items</p><p className="mt-1 flex items-center gap-1 text-[10px] text-muted-foreground sm:justify-end"><Clock3 className="size-3" />{item.date}</p></div></div>)}</div></div>
    <div className="identia-card p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Identity coverage</h2><p className="mt-1 text-xs text-muted-foreground">Trusted accounts in your core</p></div><Fingerprint className="size-5 text-teal" /></div><div className="mt-6 space-y-5">{accounts.map((account,i) => <div key={account.platform}><div className="mb-2 flex justify-between text-xs"><span className="font-semibold">{account.platform}</span><span className="text-muted-foreground">Verified</span></div><div className="h-2 rounded-full bg-muted"><div className={`h-full rounded-full bg-teal ${i === 0 ? "w-[92%]" : i === 1 ? "w-[85%]" : "w-[78%]"}`} /></div></div>)}</div><div className="mt-7 rounded-lg bg-navy-soft p-4"><p className="text-xs font-bold text-primary">Strengthen your identity core</p><p className="mt-1 text-[11px] leading-5 text-muted-foreground">Add a personal website to improve cross-platform matching.</p><Button variant="link" size="sm" asChild className="mt-1 h-auto p-0"><Link to="/identity-core">Add account <ArrowRight /></Link></Button></div></div></section>
  </div></AppShell>;
}