import { Link, createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, Github, Instagram, Linkedin, Link2, Plus, ScanSearch, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/identia-app-shell";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { accounts } from "@/lib/identia-data";

export const Route = createFileRoute("/identity-core")({ head: () => ({ meta: [{ title: "Identity Core — IDENTIA" }, { name: "description", content: "Manage the verified profiles that define your online identity." }, { property: "og:title", content: "Identity Core — IDENTIA" }, { property: "og:description", content: "Your trusted online accounts in one verified identity core." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: IdentityCore });

const icons = { Instagram, GitHub: Github, LinkedIn: Linkedin };
function IdentityCore() {
  const [open, setOpen] = useState(false); const [added, setAdded] = useState(false);
    <div className="flex flex-col gap-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><p className="max-w-2xl text-sm leading-6 text-muted-foreground">These verified profiles form your reference identity. IDENTIA compares potential impersonators against this trusted core.</p><div className="flex flex-wrap gap-2"><Button variant="outline" asChild><Link to="/shadow-check"><ScanSearch />Scan the public web</Link></Button><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus />Add account</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Add a trusted account</DialogTitle><DialogDescription>Paste a public profile URL. This preview will add a sample website.</DialogDescription></DialogHeader><div className="space-y-2 py-3"><label htmlFor="profile-url" className="text-xs font-bold">Profile URL</label><Input id="profile-url" placeholder="https://example.com/your-profile" /></div><DialogFooter><Button onClick={() => {setAdded(true);setOpen(false)}}>Verify account</Button></DialogFooter></DialogContent></Dialog></div></div>
    <section className="grid gap-5 lg:grid-cols-3">{accounts.map((account) => {const Icon=icons[account.platform]; const tone=account.color==="plum"?"bg-plum-soft text-plum":account.color==="teal"?"bg-teal-soft text-teal":"bg-secondary text-foreground"; return <article key={account.platform} className="identia-card p-6"><div className="flex items-start justify-between"><span className={`grid size-12 place-items-center rounded-lg ${tone}`}><Icon className="size-6" /></span><span className="flex items-center gap-1 rounded-full bg-teal-soft px-2.5 py-1 text-[10px] font-bold text-teal"><CheckCircle2 className="size-3"/>Verified</span></div><p className="mt-6 text-xs font-semibold text-muted-foreground">{account.platform}</p><h2 className="mt-1 text-lg font-bold">{account.handle}</h2><p className="mt-1 text-xs text-muted-foreground">{account.audience}</p><div className="mt-6 border-t border-border pt-4"><p className="text-[10px] uppercase text-muted-foreground">Verified on</p><p className="mt-1 text-xs font-semibold">{account.verified}</p></div></article>})}{added && <article className="identia-card p-6"><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-lg bg-amber-soft text-foreground"><Link2 className="size-6" /></span><span className="flex items-center gap-1 rounded-full bg-teal-soft px-2.5 py-1 text-[10px] font-bold text-teal"><CheckCircle2 className="size-3"/>Verified</span></div><p className="mt-6 text-xs font-semibold text-muted-foreground">Website</p><h2 className="mt-1 text-lg font-bold">mayarivera.design</h2><p className="mt-1 text-xs text-muted-foreground">Personal portfolio</p></article>}</section>
    <section className="rounded-lg bg-primary p-6 text-primary-foreground sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-lg bg-sidebar-accent"><ShieldCheck className="size-6 text-teal" /></span><div><h2 className="font-bold">Core confidence: Strong</h2><p className="mt-1 max-w-xl text-xs leading-5 text-primary-foreground/60">Your three profiles share enough consistent signals for reliable comparison.</p></div></div><span className="font-display text-3xl font-bold text-amber">92%</span></div></section>
  </div></AppShell>;
}