import { createFileRoute } from "@tanstack/react-router";
import { AlertTriangle, CheckCircle2, ExternalLink, Image, LoaderCircle, ScanSearch, ShieldAlert } from "lucide-react";
import { useState, type FormEvent } from "react";
import { AppShell } from "@/components/identia-app-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export const Route = createFileRoute("/shadow-check")({ head: () => ({ meta: [{ title: "Shadow Check — IDENTIA" }, { name: "description", content: "Check a username or profile URL for signs of online impersonation." }, { property: "og:title", content: "Shadow Check — IDENTIA" }, { property: "og:description", content: "Review public profile signals against your trusted identity." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ShadowCheck });

function ShadowCheck(){const [query,setQuery]=useState("");const [state,setState]=useState<"idle"|"scanning"|"done">("idle");const run=(e:FormEvent)=>{e.preventDefault();setState("scanning");window.setTimeout(()=>setState("done"),900)};return <AppShell eyebrow="Profile analysis" title="Shadow Check"><div className="mx-auto max-w-4xl"><section className="identia-card p-6 sm:p-8"><div className="flex gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-lg bg-plum-soft text-plum"><ScanSearch className="size-6"/></span><div><h2 className="text-lg font-bold">Check a public profile</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Enter a username or profile URL to compare it with your verified identity signals.</p></div></div><form onSubmit={run} className="mt-7 flex flex-col gap-3 sm:flex-row"><Input required value={query} onChange={e=>setQuery(e.target.value)} placeholder="@username or https://social.example/profile" className="h-11"/><Button type="submit" size="lg" disabled={state==="scanning"}>{state==="scanning"?<LoaderCircle className="animate-spin"/>:<ScanSearch/>}{state==="scanning"?"Checking…":"Run check"}</Button></form><p className="mt-3 text-[11px] text-muted-foreground">Try “@maya.rivera_official” to preview a result.</p></section>{state==="done"&&<section className="identia-card mt-6 overflow-hidden"><div className="flex flex-col gap-4 border-b border-border bg-plum-soft p-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-lg bg-plum text-primary-foreground"><ShieldAlert className="size-5"/></span><div><p className="text-xs font-bold uppercase text-plum">High similarity detected</p><h2 className="mt-1 font-bold">@maya.rivera_official</h2></div></div><span className="font-display text-3xl font-bold text-plum">86%</span></div><div className="grid gap-6 p-6 sm:grid-cols-2"><div><h3 className="text-xs font-bold uppercase text-muted-foreground">Matched signals</h3><div className="mt-4 space-y-3">{[[Image,"Profile photo","Exact visual match"],[CheckCircle2,"Display name","Maya Rivera"],[ExternalLink,"Bio link","Redirects to unrelated page"]].map(([Icon,label,detail])=><div key={String(label)} className="flex items-center gap-3 rounded-md border border-border p-3"><Icon className="size-4 text-plum"/><div><p className="text-xs font-bold">{String(label)}</p><p className="text-[10px] text-muted-foreground">{String(detail)}</p></div></div>)}</div></div><div className="rounded-lg bg-amber-soft p-5"><div className="flex gap-3"><AlertTriangle className="size-5 shrink-0 text-foreground"/><div><h3 className="text-sm font-bold">Recommended next step</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">Review the profile manually, then preserve the URL and visible details in a new evidence case.</p><Button className="mt-5" size="sm">Save as case</Button></div></div></div></div></section>}</div></AppShell>}